accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('edit/', views.edit_user, name='edit')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path('detail/<slug:slug>', views.article_detail, name="article_detail"),
    path('category/<int:pk>', views.category_detail, name='category_detail'),
    path('list/', views.article_list, name='article_list'),
    path('search/', views.search, name='search'),
    path('contactus/', views.ContactUsView.as_view(), name='contactus'),
]

standblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('article/', include('blog.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fathers_name = models.CharField(max_length=50)
    melicode = models.CharField(max_length=10)
    image = models.ImageField(upload_to="profiles/images", blank=True, null=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'حساب کاربری'
        verbose_name_plural = 'حساب های کاربری'

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.forms import ValidationError
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.Textarea(attrs={'class': 'input100'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input100'}))

    def clean_password(self):
        user = authenticate(username=self.cleaned_data.get('username'), password=self.cleaned_data.get('password'))
        if user is not None:
            return self.cleaned_data.get('password')
        raise ValidationError('username or password are wrong', code='invalid_info')


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import LoginForm, UserEditForm
from django.views.generic.base import View


# Create your views here.
def login_user(request):
    if request.user.is_authenticated:
        return redirect('home:home')

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = User.objects.get(username=form.cleaned_data.get('username'))
            login(request, user)
            return redirect('home:home')
    else:
        form = LoginForm
    return render(request, 'accounts/login.html', {'form': form})


def register_user(request):
    context = {'errors': []}
    if request.user.is_authenticated:
        return redirect('home:home')

    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password1 != password2:
            context['errors'].append('passwords are not same')
            return render(request, 'accounts/register.html', context)

        user = User.objects.create(username=username, password=password1, email=email)
        login(request, user)
        return redirect('home:home')

    return render(request, 'accounts/register.html')


def edit_user(request):
    user = request.user
    form = UserEditForm(instance=user)
    if request.method == "POST":
        form = UserEditForm(instance=user, data=request.POST)
        if form.is_valid():
            form.save()
    return render(request, 'accounts/edit.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('home:home')

accounts/templates/accounts/edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
contactus
{% endblock %}

{% block content %}
<section class="contact-us">
    <div class="container">
        <div class="row">

            <div class="col-lg-12">
                <div class="down-contact">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="sidebar-item contact-form">
                                <div class="sidebar-heading">
                                    <h2>Edit your profile</h2>
                                </div>
                                <div class="content">
                                    <form id="contact" action="" method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            {{ form }}
                                            <div class="col-lg-12">
                                                <fieldset>
                                                    <button type="submit" id="form-submit" class="main-button">Send
                                                    </button>
                                                </fieldset>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="sidebar-item contact-information">
                                <div class="sidebar-heading">
                                    <h2>contact information</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        <li>
                                            <h5>090-484-8080</h5>
                                            <span>PHONE NUMBER</span>
                                        </li>
                                        <li>
                                            <h5>info@company.com</h5>
                                            <span>EMAIL ADDRESS</span>
                                        </li>
                                        <li>
                                            <h5>123 Aenean id posuere dui,
                                                <br>Praesent laoreet 10660</h5>
                                            <span>STREET ADDRESS</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-12">
                <div id="map">
                    <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                            width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
            </div>

        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V3</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{ static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' }">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

<div class="limiter">
	{% csrf_token %}
</div>
<div class="limiter">
	<div class="container-login100" style="background-image: url('{% static " images
	/bg-01.jpg" %}');">
	<div class="wrap-login100">
		<form class="login100-form validate-form" , method="post">
			{% csrf_token %}
			<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

			<span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>
			<p>{{ forms.errors }}</p>
			<div class="wrap-input100 validate-input" data-validate="Enter username">
				{{ form.username }}
				<span class="focus-input100" data-placeholder="&#xf207;"></span>
			</div>

			<div class="wrap-input100 validate-input" data-validate="Enter password">
				{{ form.password }}
				<span class="focus-input100" data-placeholder="&#xf191;"></span>
			</div>

			<div class="contact100-form-checkbox">
				<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
				<label class="label-checkbox100" for="ckb1">
					Remember me
				</label>
			</div>

			<div class="container-login100-form-btn">
				<button class="login100-form-btn">
					Login
				</button>
			</div>

			<div class="text-center p-t-90">
				<a class="txt1" href="#">
					Forgot Password?
				</a>
			</div>
		</form>
	</div>
</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js'  %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Register</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static "images/icons/favicon.ico" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{ static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" }">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "fonts/iconic/css/material-design-iconic-font.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "vendor/animate/animate.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "vendor/css-hamburgers/hamburgers.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "vendor/animsition/css/animsition.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "vendor/select2/select2.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "vendor/daterangepicker/daterangepicker.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static "images/bg-01.jpg" %}');">
			<div class="wrap-login100">
				<form class="login100-form validate-form", method="post">
					{% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Register
					</span>

					{% if errors %}
						{% for item in errors %}
							<p class="text text-danger bg-white rounded mb-2">{{ item }}</p>
						{% endfor %}
					{% endif %}

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "email">
						<input class="input100" type="text" name="email" placeholder="Email">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password1" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password2" placeholder="Repeat Password">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Register
						</button>
					</div>

					<div class="text-center p-t-90">
						<a class="txt1" href="{% url 'accounts:login' %}">
							Login
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static "vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "vendor/animsition/js/animsition.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "vendor/bootstrap/js/popper.js" %}"></script>
	<script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "vendor/select2/select2.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "vendor/daterangepicker/moment.min.js" %}"></script>
	<script src="{% static "vendor/daterangepicker/daterangepicker.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "vendor/countdowntime/countdowntime.js"  %}"></script>
<!--===============================================================================================-->
	<script src="{% static "js/main.js" %}"></script>

</body>
</html>