blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path('detail/<slug:slug>', views.article_detail, name="article_detail"),
    path('category/<int:pk>', views.category_detail, name='category_detail'),
    path('list/', views.article_list, name='article_list'),
    path('search/', views.search, name='search'),
    path('contactus/', views.ContactUsView.as_view(), name='contactus'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('sidebar', views.sidebar, name="sidebar_partial")
]

standblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('article/', include('blog.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
{% load static %}
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="social-icons">
          <li><a href="#">Facebook</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Behance</a></li>
          <li><a href="#">Linkedin</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
      <div class="col-lg-12">
        <div class="copyright-text">
          <p>Copyright 2020 Stand Blog Co.

              | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer_references.html
{% load static %}
<!-- Bootstrap core JavaScript -->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<!-- Additional Scripts -->
<script src="{% static "js/custom.js" %}"></script>
<script src="{% static "js/owl.js" %}"></script>
<script src="{% static "js/slick.js" %}"></script>
<script src="{% static "js/isotope.js" %}"></script>
<script src="{% static "js/accordions.js" %}"></script>

<script language = "text/Javascript">
  cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
  function clearField(t){                   //declaring the array outside of the
  if(! cleared[t.id]){                      // function makes it static and global
      cleared[t.id] = 1;  // you could use true and false, but that's more typing
      t.value='';         // with more chance of typos
      t.style.color='#fff';
      }
  }
</script>

templates/includes/head_references.html
{% load static %}
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

<title>{% block title %}{% endblock %}</title>

<!-- Bootstrap core CSS -->
<link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">


<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static "css/fontawesome.css" %}">
<link rel="stylesheet" href="{% static "css/templatemo-stand-blog.css" %}">
<link rel="stylesheet" href="{% static "css/owl.css" %}">
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
</head>

templates/includes/header.html
{% load static %}
<!-- Header -->
<header class="">
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home:home' %}"><h2>Stand Blog<em>.</em></h2></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item {% if request.resolver_match.url_name == 'home' %} active {% endif %}">
            <a class="nav-link" href="{% url 'home:home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'article_list' %} active {% endif %} " href="{% url 'blog:article_list' %}">All Articles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post-details.html">Post Details</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:contactus' %}">Contact Us</a>
          </li>
          <li class="nav-item">
            {% if request.user.is_authenticated %}
              <div class="d-flex">
                {% if request.user.username %}
                  <a class="nav-link" href="">{{ request.user.username }}</a>
                {% else %}
                  <a class="nav-link" href="">{{ request.user.username }}</a>
                {% endif %}
                <a href="/logout"><span class="badge badge-danger mt-2">logout</span></a>
              </div>
            {% else %}
              <div class="d-flex">
                <a class="nav-link" href="/login">login</a><span class="mt-2">/</span>
                <a class="nav-link" href="/register">register</a>
              </div>
            {% endif %}

          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

templates/includes/sidebar.html
{% load static  %}
<div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item search">
                                <form id="search_form" name="gs" method="GET" action="{% url 'blog:search' %}">
                                    <input type="text" name="q" class="searchText" placeholder="type to search..."
                                           autocomplete="on">
                                </form>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item recent-posts">
                                <div class="sidebar-heading">
                                    <h2>Recent Posts</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        {% for article in recent_article %}
                                        <li><a href="post-details.html">
                                            <h5>{{ article.title }}</h5>
                                            <span>{{ article.create }}</span>
                                        </a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item categories">
                                <div class="sidebar-heading">
                                    <h2>Categories</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        {% for category in categories %}
                                            <li><a href="{% url 'blog:category_detail' category.id %}">- {{ category.title }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item tags">
                                <div class="sidebar-heading">
                                    <h2>Tag Clouds</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        <li><a href="#">Lifestyle</a></li>
                                        <li><a href="#">Creative</a></li>
                                        <li><a href="#">HTML5</a></li>
                                        <li><a href="#">Inspiration</a></li>
                                        <li><a href="#">Motivation</a></li>
                                        <li><a href="#">PSD</a></li>
                                        <li><a href="#">Responsive</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>